export const initialEditors = [
  {
    id: 'e1',
    email: 'marcus@gogangs.com',
    password: 'demo1234',
    fullName: 'Marcus Chen',
    phone: '+1 (415) 555-0142',
    city: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/marcuschen',
    instagram: '@marcus.edits',
    portfolioLink: 'marcuschen.studio',
    experience: 6,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    skills: ['Reels Editing', 'YouTube Editing', 'Motion Graphics', 'Color Grading'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Award-winning video editor specializing in cinematic YouTube content and short-form social media. 6 years of experience working with creators and brands to craft compelling visual narratives.',
    avatarUrl: 'https://i.pravatar.cc/150?u=marcus',
    portfolio: [
      { id: 'p1', title: 'Cinematic Travel Reel — Tokyo Nights', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo1', featured: true },
      { id: 'p2', title: 'Brand Commercial — Aurora Skincare', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo2', featured: true },
      { id: 'p3', title: 'Motion Graphics Package — TechFlow SaaS', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo3', featured: true },
      { id: 'p4', title: 'Wedding Highlight Film — Sarah & James', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo4', featured: false },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/marcus-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo1', 'https://youtube.com/watch?v=demo2'], portfolioLinks: ['marcuschen.studio'] },
    active: true,
    lastLogin: '2026-08-18T09:30:00Z',
    lastProfileUpdate: '2026-08-15T14:20:00Z',
    lastPortfolioUpdate: '2026-08-12T11:00:00Z',
    isFeatured: true,
  },
  {
    id: 'e2',
    email: 'elena@gogangs.com',
    password: 'demo1234',
    fullName: 'Elena Rodriguez',
    phone: '+1 (212) 555-0198',
    city: 'New York, NY',
    linkedin: 'linkedin.com/in/elenarodriguez',
    instagram: '@elena.creates',
    portfolioLink: 'elenarodriguez.video',
    experience: 4,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'CapCut'],
    skills: ['Reels Editing', 'Commercial Ads', 'Thumbnail Design'],
    availability: 'Part-Time',
    hoursPerWeek: 25,
    bio: 'Creative editor focused on high-impact social media content and commercial advertising. Based in NYC, working with fashion and lifestyle brands.',
    avatarUrl: 'https://i.pravatar.cc/150?u=elena',
    portfolio: [
      { id: 'p5', title: 'Fashion Week Recap — NYFW 2026', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo5', featured: true },
      { id: 'p6', title: 'Product Launch — Lumen Cosmetics', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo6', featured: true },
      { id: 'p7', title: 'Instagram Reel Series — Bloom Skincare', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo7', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/elena-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo5'], portfolioLinks: ['elenarodriguez.video'] },
    active: true,
    lastLogin: '2026-08-17T16:45:00Z',
    lastProfileUpdate: '2026-08-14T10:15:00Z',
    lastPortfolioUpdate: '2026-08-10T09:00:00Z',
  },
  {
    id: 'e3',
    email: 'david@gogangs.com',
    password: 'demo1234',
    fullName: 'David Park',
    phone: '+1 (310) 555-0173',
    city: 'Los Angeles, CA',
    linkedin: 'linkedin.com/in/davidpark',
    portfolioLink: 'davidpark.edits',
    experience: 8,
    editingSoftware: ['Adobe Premiere Pro', 'DaVinci Resolve', 'Adobe Audition'],
    skills: ['YouTube Editing', 'Podcast Editing', 'Color Grading', 'Corporate Videos'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Veteran editor with 8 years in the industry. Specializing in long-form YouTube content, podcast production, and corporate video. Color grading specialist with DaVinci Resolve expertise.',
    avatarUrl: 'https://i.pravatar.cc/150?u=david',
    portfolio: [
      { id: 'p8', title: 'Documentary Series — Ocean Explorers', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo8', featured: true },
      { id: 'p9', title: 'Podcast Visualizer — The Growth Lab', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo9', featured: true },
      { id: 'p10', title: 'Corporate Brand Film — Nexus Technologies', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo10', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/david-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo8'], portfolioLinks: ['davidpark.edits'] },
    active: true,
    lastLogin: '2026-08-18T08:00:00Z',
    lastProfileUpdate: '2026-08-16T13:30:00Z',
    lastPortfolioUpdate: '2026-08-14T15:00:00Z',
    isFeatured: true,
  },
  {
    id: 'e4',
    email: 'priya@gogangs.com',
    password: 'demo1234',
    fullName: 'Priya Sharma',
    phone: '+44 20 7946 0958',
    city: 'London, UK',
    linkedin: 'linkedin.com/in/priyasharma',
    instagram: '@priya.films',
    portfolioLink: 'priyasharma.films',
    experience: 5,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'Adobe Photoshop'],
    skills: ['Wedding Videos', 'Motion Graphics', 'Commercial Ads'],
    availability: 'Weekends',
    hoursPerWeek: 15,
    bio: 'Wedding cinematography and motion graphics specialist based in London. Creating emotional, cinematic wedding films and elegant motion design for brands.',
    avatarUrl: 'https://i.pravatar.cc/150?u=priya',
    portfolio: [
      { id: 'p11', title: 'Wedding Film — Amara & Daniel', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo11', featured: true },
      { id: 'p12', title: 'Motion Design Reel 2026', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo12', featured: true },
      { id: 'p13', title: 'Luxury Resort Promo — Azure Maldives', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo13', featured: true },
    ],
    verificationStatus: 'Pending',
    verificationDocs: { resumeLink: 'https://docs.google.com/priya-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo11'], portfolioLinks: ['priyasharma.films'] },
    active: true,
    lastLogin: '2026-08-17T19:00:00Z',
    lastProfileUpdate: '2026-08-17T19:30:00Z',
    lastPortfolioUpdate: '2026-08-16T18:00:00Z',
  },
  {
    id: 'e5',
    email: 'james@gogangs.com',
    password: 'demo1234',
    fullName: 'James Wilson',
    phone: '+1 (312) 555-0167',
    city: 'Chicago, IL',
    linkedin: 'linkedin.com/in/jameswilson',
    portfolioLink: 'jwilson.video',
    experience: 3,
    editingSoftware: ['Adobe Premiere Pro', 'CapCut'],
    skills: ['Reels Editing', 'YouTube Editing', 'Thumbnail Design'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Fast-rising editor specializing in short-form content and YouTube growth. Helping creators scale from 10K to 100K subscribers with engaging edits.',
    avatarUrl: 'https://i.pravatar.cc/150?u=james',
    portfolio: [
      { id: 'p14', title: 'Viral Reel Series — FitnessPro', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo14', featured: true },
      { id: 'p15', title: 'YouTube Channel Package — TechTalk Daily', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo15', featured: true },
      { id: 'p16', title: 'Thumbnail Design Set — Growth Lab', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo16', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/james-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo14'], portfolioLinks: ['jwilson.video'] },
    active: true,
    lastLogin: '2026-08-18T07:15:00Z',
    lastProfileUpdate: '2026-08-13T11:45:00Z',
    lastPortfolioUpdate: '2026-08-11T14:00:00Z',
  }
];

export const initialProjects = [
  {
    id: 'p1',
    title: 'Aurora Skincare — Q4 Launch Campaign',
    clientName: 'Aurora Cosmetics Inc.',
    description: 'Full video asset production for nationwide skincare launch across Instagram, TikTok, and YouTube.',
    status: 'In Progress',
    subtasks: [
      {
        id: 'st-1',
        title: 'Hero Brand Film (60s)',
        taskType: 'Commercial Ads',
        assignedEditorIds: ['e1', 'e2'],
        deadline: '2025-05-19T23:59:59Z',
        status: 'In Progress'
      },
      {
        id: 'st-2',
        title: 'Instagram Reel Series (5x)',
        taskType: 'Reels Editing',
        assignedEditorIds: ['e2'],
        deadline: '2025-05-20T23:59:59Z',
        status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/aurora-reels'
      },
      {
        id: 'st-3',
        title: 'Product Tutorial Videos (3x)',
        taskType: 'YouTube Editing',
        assignedEditorIds: ['e1'],
        deadline: '2025-05-25T23:59:59Z',
        status: 'Assigned'
      },
      {
        id: 'st-4',
        title: 'Thumbnail Design Package',
        taskType: 'Thumbnail Design',
        assignedEditorIds: ['e3'],
        deadline: '2025-05-20T23:59:59Z',
        status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/aurora-thumbs'
      }
    ]
  },
  {
    id: 'p2',
    title: 'TechFlow SaaS — Product Demo Series',
    clientName: 'TechFlow Inc.',
    description: 'SaaS product demo video series highlighting automated workflow features.',
    status: 'In Progress',
    subtasks: [
      {
        id: 'st-5',
        title: 'Motion Graphics Intro Package',
        taskType: 'Motion Graphics',
        assignedEditorIds: ['e1'],
        deadline: '2025-05-21T23:59:59Z',
        status: 'In Progress'
      },
      {
        id: 'st-6',
        title: 'Feature Walkthrough Video',
        taskType: 'YouTube Editing',
        assignedEditorIds: ['e3'],
        deadline: '2025-05-22T23:59:59Z',
        status: 'In Progress'
      },
      {
        id: 'st-7',
        title: 'Social Teasers (4x)',
        taskType: 'Reels Editing',
        assignedEditorIds: ['e2'],
        deadline: '2025-05-21T23:59:59Z',
        status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/techflow-teasers'
      }
    ]
  }
];
