import type { Editor, Project, ActivityEvent } from './types';

const avatarSeeds = [
  'marcus', 'elena', 'david', 'priya', 'james', 'sofia', 'liam', 'aria',
  'noah', 'zara', 'ethan', 'maya', 'lucas', 'nora', 'leo',
];

function avatar(seed: string): string {
  return `https://i.pravatar.cc/150?u=${seed}`;
}

export const editors: Editor[] = [
  {
    id: 'e1',
    email: 'marcus@gogangs.com',
    password: 'demo1234',
    fullName: 'Marcus Chen',
    phone: '+1 (415) 555-0142',
    city: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/marcuschen',
    instagram: '@marcus.edits',
    portfolioLink: 'marcuschen.studio',
    experience: 6,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    skills: ['Reels Editing', 'YouTube Editing', 'Motion Graphics', 'Color Grading'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Award-winning video editor specializing in cinematic YouTube content and short-form social media. 6 years of experience working with creators and brands to craft compelling visual narratives.',
    avatarUrl: avatar(avatarSeeds[0]),
    portfolio: [
      { id: 'p1', title: 'Cinematic Travel Reel — Tokyo Nights', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo1', featured: true },
      { id: 'p2', title: 'Brand Commercial — Aurora Skincare', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo2', featured: true },
      { id: 'p3', title: 'Motion Graphics Package — TechFlow SaaS', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo3', featured: true },
      { id: 'p4', title: 'Wedding Highlight Film — Sarah & James', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo4', featured: false },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/marcus-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo1', 'https://youtube.com/watch?v=demo2'], portfolioLinks: ['marcuschen.studio'] },
    active: true,
    lastLogin: '2026-08-18T09:30:00Z',
    lastProfileUpdate: '2026-08-15T14:20:00Z',
    lastPortfolioUpdate: '2026-08-12T11:00:00Z',
    isFeatured: true,
  },
  {
    id: 'e2',
    email: 'elena@gogangs.com',
    password: 'demo1234',
    fullName: 'Elena Rodriguez',
    phone: '+1 (212) 555-0198',
    city: 'New York, NY',
    linkedin: 'linkedin.com/in/elenarodriguez',
    instagram: '@elena.creates',
    portfolioLink: 'elenarodriguez.video',
    experience: 4,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'CapCut'],
    skills: ['Reels Editing', 'Commercial Ads', 'Thumbnail Design'],
    availability: 'Part-Time',
    hoursPerWeek: 25,
    bio: 'Creative editor focused on high-impact social media content and commercial advertising. Based in NYC, working with fashion and lifestyle brands.',
    avatarUrl: avatar(avatarSeeds[1]),
    portfolio: [
      { id: 'p5', title: 'Fashion Week Recap — NYFW 2026', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo5', featured: true },
      { id: 'p6', title: 'Product Launch — Lumen Cosmetics', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo6', featured: true },
      { id: 'p7', title: 'Instagram Reel Series — Bloom Skincare', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo7', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/elena-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo5'], portfolioLinks: ['elenarodriguez.video'] },
    active: true,
    lastLogin: '2026-08-17T16:45:00Z',
    lastProfileUpdate: '2026-08-14T10:15:00Z',
    lastPortfolioUpdate: '2026-08-10T09:00:00Z',
  },
  {
    id: 'e3',
    email: 'david@gogangs.com',
    password: 'demo1234',
    fullName: 'David Park',
    phone: '+1 (310) 555-0173',
    city: 'Los Angeles, CA',
    linkedin: 'linkedin.com/in/davidpark',
    portfolioLink: 'davidpark.edits',
    experience: 8,
    editingSoftware: ['Adobe Premiere Pro', 'DaVinci Resolve', 'Adobe Audition'],
    skills: ['YouTube Editing', 'Podcast Editing', 'Color Grading', 'Corporate Videos'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Veteran editor with 8 years in the industry. Specializing in long-form YouTube content, podcast production, and corporate video. Color grading specialist with DaVinci Resolve expertise.',
    avatarUrl: avatar(avatarSeeds[2]),
    portfolio: [
      { id: 'p8', title: 'Documentary Series — Ocean Explorers', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo8', featured: true },
      { id: 'p9', title: 'Podcast Visualizer — The Growth Lab', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo9', featured: true },
      { id: 'p10', title: 'Corporate Brand Film — Nexus Technologies', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo10', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/david-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo8'], portfolioLinks: ['davidpark.edits'] },
    active: true,
    lastLogin: '2026-08-18T08:00:00Z',
    lastProfileUpdate: '2026-08-16T13:30:00Z',
    lastPortfolioUpdate: '2026-08-14T15:00:00Z',
    isFeatured: true,
  },
  {
    id: 'e4',
    email: 'priya@gogangs.com',
    password: 'demo1234',
    fullName: 'Priya Sharma',
    phone: '+44 20 7946 0958',
    city: 'London, UK',
    linkedin: 'linkedin.com/in/priyasharma',
    instagram: '@priya.films',
    portfolioLink: 'priyasharma.films',
    experience: 5,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'Adobe Photoshop'],
    skills: ['Wedding Videos', 'Motion Graphics', 'Commercial Ads'],
    availability: 'Weekends',
    hoursPerWeek: 15,
    bio: 'Wedding cinematography and motion graphics specialist based in London. Creating emotional, cinematic wedding films and elegant motion design for brands.',
    avatarUrl: avatar(avatarSeeds[3]),
    portfolio: [
      { id: 'p11', title: 'Wedding Film — Amara & Daniel', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo11', featured: true },
      { id: 'p12', title: 'Motion Design Reel 2026', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo12', featured: true },
      { id: 'p13', title: 'Luxury Resort Promo — Azure Maldives', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo13', featured: true },
    ],
    verificationStatus: 'Pending',
    verificationDocs: { resumeLink: 'https://docs.google.com/priya-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo11'], portfolioLinks: ['priyasharma.films'] },
    active: true,
    lastLogin: '2026-08-17T19:00:00Z',
    lastProfileUpdate: '2026-08-17T19:30:00Z',
    lastPortfolioUpdate: '2026-08-16T18:00:00Z',
  },
  {
    id: 'e5',
    email: 'james@gogangs.com',
    password: 'demo1234',
    fullName: 'James Wilson',
    phone: '+1 (312) 555-0167',
    city: 'Chicago, IL',
    linkedin: 'linkedin.com/in/jameswilson',
    portfolioLink: 'jwilson.video',
    experience: 3,
    editingSoftware: ['Adobe Premiere Pro', 'CapCut'],
    skills: ['Reels Editing', 'YouTube Editing', 'Thumbnail Design'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Fast-rising editor specializing in short-form content and YouTube growth. Helping creators scale from 10K to 100K subscribers with engaging edits.',
    avatarUrl: avatar(avatarSeeds[4]),
    portfolio: [
      { id: 'p14', title: 'Viral Reel Series — FitnessPro', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo14', featured: true },
      { id: 'p15', title: 'YouTube Channel Package — TechTalk Daily', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo15', featured: true },
      { id: 'p16', title: 'Thumbnail Design Set — Growth Lab', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo16', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/james-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo14'], portfolioLinks: ['jwilson.video'] },
    active: true,
    lastLogin: '2026-08-18T07:15:00Z',
    lastProfileUpdate: '2026-08-13T11:45:00Z',
    lastPortfolioUpdate: '2026-08-11T14:00:00Z',
  },
  {
    id: 'e6',
    email: 'sofia@gogangs.com',
    password: 'demo1234',
    fullName: 'Sofia Almeida',
    phone: '+55 11 95555 0188',
    city: 'São Paulo, Brazil',
    instagram: '@sofia.motion',
    portfolioLink: 'sofiaalmeida.motion',
    experience: 7,
    editingSoftware: ['After Effects', 'Adobe Premiere Pro', 'Adobe Photoshop'],
    skills: ['Motion Graphics', 'Commercial Ads', 'Corporate Videos'],
    availability: 'Part-Time',
    hoursPerWeek: 30,
    bio: 'Motion designer and commercial editor with 7 years of experience creating broadcast-quality animations and ad campaigns for global brands.',
    avatarUrl: avatar(avatarSeeds[5]),
    portfolio: [
      { id: 'p17', title: 'Broadcast Package — SportsNet Brasil', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo17', featured: true },
      { id: 'p18', title: 'Product Animation — Vortex Headphones', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo18', featured: true },
      { id: 'p19', title: 'Corporate Explainer — FinBank', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo19', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/sofia-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo17'], portfolioLinks: ['sofiaalmeida.motion'] },
    active: true,
    lastLogin: '2026-08-16T20:00:00Z',
    lastProfileUpdate: '2026-08-15T09:00:00Z',
    lastPortfolioUpdate: '2026-08-14T16:00:00Z',
  },
  {
    id: 'e7',
    email: 'liam@gogangs.com',
    password: 'demo1234',
    fullName: 'Liam O\'Brien',
    phone: '+353 1 555 0193',
    city: 'Dublin, Ireland',
    linkedin: 'linkedin.com/in/liamobrien',
    portfolioLink: 'liamobrien.audio',
    experience: 4,
    editingSoftware: ['Adobe Audition', 'Adobe Premiere Pro'],
    skills: ['Podcast Editing', 'YouTube Editing'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Audio-first editor specializing in podcast production and YouTube content. Expert in dialogue cleanup, sound design, and multi-cam editing.',
    avatarUrl: avatar(avatarSeeds[6]),
    portfolio: [
      { id: 'p20', title: 'Podcast Series — The Founder\'s Journey', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo20', featured: true },
      { id: 'p21', title: 'YouTube Talk Show — Dublin Tech Talks', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo21', featured: true },
      { id: 'p22', title: 'Audio Drama — Whispers of Dublin', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo22', featured: true },
    ],
    verificationStatus: 'Pending',
    verificationDocs: { resumeLink: 'https://docs.google.com/liam-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo20'], portfolioLinks: ['liamobrien.audio'] },
    active: true,
    lastLogin: '2026-08-18T06:00:00Z',
    lastProfileUpdate: '2026-08-17T22:00:00Z',
    lastPortfolioUpdate: '2026-08-17T21:00:00Z',
  },
  {
    id: 'e8',
    email: 'aria@gogangs.com',
    password: 'demo1234',
    fullName: 'Aria Patel',
    phone: '+1 (206) 555-0156',
    city: 'Seattle, WA',
    linkedin: 'linkedin.com/in/ariapatel',
    instagram: '@aria.color',
    portfolioLink: 'ariapatel.color',
    experience: 5,
    editingSoftware: ['DaVinci Resolve', 'Adobe Premiere Pro'],
    skills: ['Color Grading', 'Wedding Videos', 'Corporate Videos'],
    availability: 'Part-Time',
    hoursPerWeek: 20,
    bio: 'Color grading specialist with a background in wedding cinematography and corporate video. Certified DaVinci Resolve colorist.',
    avatarUrl: avatar(avatarSeeds[7]),
    portfolio: [
      { id: 'p23', title: 'Color Reel — Cinematic Grades 2026', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo23', featured: true },
      { id: 'p24', title: 'Wedding Film — Emily & Ryan', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo24', featured: true },
      { id: 'p25', title: 'Corporate Color Grade — Summit Realty', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo25', featured: true },
    ],
    verificationStatus: 'Rejected',
    verificationFeedback: 'Your portfolio shows strong color grading work, but we need to see more diversity in your editing styles. Please add at least 2 examples of narrative or commercial editing, and ensure your resume link is publicly accessible.',
    verificationDocs: { resumeLink: 'https://docs.google.com/aria-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo23'], portfolioLinks: ['ariapatel.color'] },
    active: true,
    lastLogin: '2026-08-15T17:00:00Z',
    lastProfileUpdate: '2026-08-14T08:00:00Z',
    lastPortfolioUpdate: '2026-08-12T10:00:00Z',
  },
  {
    id: 'e9',
    email: 'noah@gogangs.com',
    password: 'demo1234',
    fullName: 'Noah Kim',
    phone: '+1 (503) 555-0144',
    city: 'Portland, OR',
    linkedin: 'linkedin.com/in/noahkim',
    portfolioLink: 'noahkim.creative',
    experience: 2,
    editingSoftware: ['Adobe Premiere Pro', 'CapCut', 'After Effects'],
    skills: ['Reels Editing', 'YouTube Editing', 'Motion Graphics'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Emerging creative editor with a passion for social media content and motion design. Focused on helping small businesses and creators build their online presence.',
    avatarUrl: avatar(avatarSeeds[8]),
    portfolio: [
      { id: 'p26', title: 'Small Business Reels — Coffee Culture Co.', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo26', featured: true },
      { id: 'p27', title: 'YouTube Intro Package — GamerHub', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo27', featured: true },
      { id: 'p28', title: 'Motion Logo Reel — Brand Studio', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo28', featured: true },
    ],
    verificationStatus: 'Pending',
    verificationDocs: { resumeLink: 'https://docs.google.com/noah-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo26'], portfolioLinks: ['noahkim.creative'] },
    active: true,
    lastLogin: '2026-08-18T05:00:00Z',
    lastProfileUpdate: '2026-08-18T05:30:00Z',
    lastPortfolioUpdate: '2026-08-17T20:00:00Z',
  },
  {
    id: 'e10',
    email: 'zara@gogangs.com',
    password: 'demo1234',
    fullName: 'Zara Ahmed',
    phone: '+971 4 555 0162',
    city: 'Dubai, UAE',
    linkedin: 'linkedin.com/in/zaraahmed',
    instagram: '@zara.studios',
    portfolioLink: 'zaraahmed.studio',
    experience: 9,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Adobe Photoshop'],
    skills: ['Commercial Ads', 'Corporate Videos', 'Motion Graphics', 'Color Grading'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Senior editor and creative director with 9 years of experience producing premium commercial content for luxury brands across the Middle East and Europe.',
    avatarUrl: avatar(avatarSeeds[9]),
    portfolio: [
      { id: 'p29', title: 'Luxury Auto Commercial — Bentley GCC', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo29', featured: true },
      { id: 'p30', title: 'Tourism Campaign — Discover Dubai', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo30', featured: true },
      { id: 'p31', title: 'Corporate Brand Film — Emirates Tech', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo31', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/zara-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo29'], portfolioLinks: ['zaraahmed.studio'] },
    active: true,
    lastLogin: '2026-08-17T14:00:00Z',
    lastProfileUpdate: '2026-08-10T09:00:00Z',
    lastPortfolioUpdate: '2026-08-08T12:00:00Z',
    isFeatured: true,
  },
  {
    id: 'e11',
    email: 'ethan@gogangs.com',
    password: 'demo1234',
    fullName: 'Ethan Brooks',
    phone: '+1 (617) 555-0189',
    city: 'Boston, MA',
    portfolioLink: 'ethanbrooks.video',
    experience: 1,
    editingSoftware: ['Adobe Premiere Pro', 'CapCut'],
    skills: ['Reels Editing', 'Thumbnail Design'],
    availability: 'Part-Time',
    hoursPerWeek: 15,
    bio: 'Junior editor building a portfolio in short-form social content. Quick learner with a strong eye for trends and pacing.',
    avatarUrl: avatar(avatarSeeds[10]),
    portfolio: [
      { id: 'p32', title: 'Reel Collection — Local Eats Boston', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo32', featured: true },
      { id: 'p33', title: 'Thumbnail Set — SportsZone Channel', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo33', featured: true },
    ],
    verificationStatus: 'Pending',
    verificationDocs: { resumeLink: 'https://docs.google.com/ethan-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo32'], portfolioLinks: ['ethanbrooks.video'] },
    active: true,
    lastLogin: '2026-08-16T11:00:00Z',
    lastProfileUpdate: '2026-08-16T11:30:00Z',
    lastPortfolioUpdate: '2026-08-15T10:00:00Z',
  },
  {
    id: 'e12',
    email: 'maya@gogangs.com',
    password: 'demo1234',
    fullName: 'Maya Lindqvist',
    phone: '+46 8 555 0175',
    city: 'Stockholm, Sweden',
    linkedin: 'linkedin.com/in/mayalindqvist',
    instagram: '@maya.films',
    portfolioLink: 'mayalindqvist.se',
    experience: 6,
    editingSoftware: ['Final Cut Pro', 'Adobe Premiere Pro', 'DaVinci Resolve'],
    skills: ['Wedding Videos', 'Corporate Videos', 'Color Grading'],
    availability: 'Weekends',
    hoursPerWeek: 12,
    bio: 'Wedding and corporate filmmaker based in Stockholm. Known for clean, Nordic-minimalist editing style with a documentary sensibility.',
    avatarUrl: avatar(avatarSeeds[11]),
    portfolio: [
      { id: 'p34', title: 'Wedding Film — Linnea & Erik', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo34', featured: true },
      { id: 'p35', title: 'Corporate Film — Nordic Energy Co.', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo35', featured: true },
      { id: 'p36', title: 'Color Grade Reel — Nordic Light', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo36', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/maya-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo34'], portfolioLinks: ['mayalindqvist.se'] },
    active: false,
    lastLogin: '2026-07-20T10:00:00Z',
    lastProfileUpdate: '2026-07-18T09:00:00Z',
    lastPortfolioUpdate: '2026-07-15T14:00:00Z',
  },
  {
    id: 'e13',
    email: 'lucas@gogangs.com',
    password: 'demo1234',
    fullName: 'Lucas Moreira',
    phone: '+1 (305) 555-0122',
    city: 'Miami, FL',
    linkedin: 'linkedin.com/in/lucasmoreira',
    portfolioLink: 'lucasmoreira.tv',
    experience: 4,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects'],
    skills: ['Commercial Ads', 'Reels Editing', 'Motion Graphics'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Miami-based editor creating high-energy commercial and social content for fashion, music, and lifestyle brands.',
    avatarUrl: avatar(avatarSeeds[12]),
    portfolio: [
      { id: 'p37', title: 'Music Video — "Midnight" by Luna Vega', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo37', featured: true },
      { id: 'p38', title: 'Fashion Commercial — Vela Swimwear', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo38', featured: true },
      { id: 'p39', title: 'Social Media Campaign — Pulse Energy', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo39', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/lucas-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo37'], portfolioLinks: ['lucasmoreira.tv'] },
    active: true,
    lastLogin: '2026-08-18T04:00:00Z',
    lastProfileUpdate: '2026-08-12T09:00:00Z',
    lastPortfolioUpdate: '2026-08-10T11:00:00Z',
  },
  {
    id: 'e14',
    email: 'nora@gogangs.com',
    password: 'demo1234',
    fullName: 'Nora Bergstrom',
    phone: '+47 22 555 0137',
    city: 'Oslo, Norway',
    linkedin: 'linkedin.com/in/norabergstrom',
    portfolioLink: 'norabergstrom.no',
    experience: 3,
    editingSoftware: ['Adobe Premiere Pro', 'Adobe Audition'],
    skills: ['Podcast Editing', 'YouTube Editing', 'Corporate Videos'],
    availability: 'Part-Time',
    hoursPerWeek: 25,
    bio: 'Podcast and YouTube editor with a background in journalism. Specializing in narrative-driven content and interview-format shows.',
    avatarUrl: avatar(avatarSeeds[13]),
    portfolio: [
      { id: 'p40', title: 'Podcast Visualizer — Nordic Business Talks', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo40', featured: true },
      { id: 'p41', title: 'YouTube Documentary — Arctic Research', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo41', featured: true },
    ],
    verificationStatus: 'Pending',
    verificationDocs: { resumeLink: 'https://docs.google.com/nora-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo40'], portfolioLinks: ['norabergstrom.no'] },
    active: true,
    lastLogin: '2026-08-17T07:00:00Z',
    lastProfileUpdate: '2026-08-17T07:30:00Z',
    lastPortfolioUpdate: '2026-08-16T08:00:00Z',
  },
  {
    id: 'e15',
    email: 'leo@gogangs.com',
    password: 'demo1234',
    fullName: 'Leo Tanaka',
    phone: '+81 3 5555 0191',
    city: 'Tokyo, Japan',
    linkedin: 'linkedin.com/in/leotanaka',
    instagram: '@leo.edits',
    portfolioLink: 'leotanaka.jp',
    experience: 5,
    editingSoftware: ['Adobe Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Adobe Photoshop'],
    skills: ['Motion Graphics', 'YouTube Editing', 'Thumbnail Design', 'Color Grading'],
    availability: 'Full-Time',
    hoursPerWeek: 40,
    bio: 'Tokyo-based editor and motion designer. Creating content for tech, gaming, and anime channels with a distinctive visual style.',
    avatarUrl: avatar(avatarSeeds[14]),
    portfolio: [
      { id: 'p42', title: 'Gaming Channel Package — PixelQuest', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo42', featured: true },
      { id: 'p43', title: 'Motion Design Reel — Tokyo 2026', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo43', featured: true },
      { id: 'p44', title: 'Anime-Style Thumbnail Set — Otaku Central', type: 'video', thumbnailUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800', link: 'https://youtube.com/watch?v=demo44', featured: true },
    ],
    verificationStatus: 'Verified',
    verificationDocs: { resumeLink: 'https://docs.google.com/leo-resume', sampleWorkLinks: ['https://youtube.com/watch?v=demo42'], portfolioLinks: ['leotanaka.jp'] },
    active: true,
    lastLogin: '2026-08-18T03:00:00Z',
    lastProfileUpdate: '2026-08-13T08:00:00Z',
    lastPortfolioUpdate: '2026-08-11T10:00:00Z',
  },
];

export const projects: Project[] = [
  {
    id: 'proj1',
    title: 'Aurora Skincare — Q4 Launch Campaign',
    clientName: 'Aurora Cosmetics Inc.',
    createdAt: '2026-08-01T10:00:00Z',
    subtasks: [
      {
        id: 'st1', projectId: 'proj1', title: 'Hero Brand Film (60s)',
        taskType: 'Commercial Ads', deadline: '2026-08-31T23:59:00Z',
        assignedEditorIds: ['e1'], status: 'In Progress',
        deliverableLink: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800',
        feedback: 'Client reviewed v1: Please adjust the color grading on the cosmetic bottles in scene 2 to be slightly warmer, and lower the background music by -3dB when the voiceover speaks at 00:24.',
        deliverablesQueue: [
          {
            id: 'sub-st1-v1',
            version: 1,
            fileName: 'hero_brand_film_rough_cut_v1.mp4',
            fileSizeBytes: 245000000,
            fileUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800',
            mimeType: 'video/mp4',
            notes: 'Initial rough cut with temporary audio placeholder and color pass.',
            submittedAt: '2026-08-28T14:30:00Z',
            submittedByEditorId: 'e1',
            status: 'In Review',
          },
        ],
      },
      {
        id: 'st2', projectId: 'proj1', title: 'Instagram Reel Series (5x)',
        taskType: 'Reels Editing', deadline: '2026-08-20T23:59:00Z',
        assignedEditorIds: ['e2'], status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/aurora-reels',
        deliverablesQueue: [
          {
            id: 'sub-st2-v1',
            version: 1,
            fileName: 'instagram_reels_pack_v1.mp4',
            fileSizeBytes: 180000000,
            fileUrl: 'https://images.unsplash.com/photo-1608248597263-0057e43a4524?w=800',
            mimeType: 'video/mp4',
            notes: '5x vertical video exports with subtitles and sound design.',
            submittedAt: '2026-08-27T10:15:00Z',
            submittedByEditorId: 'e2',
            status: 'In Review',
          },
        ],
      },
      {
        id: 'st3', projectId: 'proj1', title: 'Product Tutorial Videos (3x)',
        taskType: 'YouTube Editing', deadline: '2026-09-06T23:59:00Z',
        assignedEditorIds: ['e1'], status: 'Assigned',
        feedback: 'Admin instructions: Please follow the brand guidelines for intro lower-thirds and include chapters in the final MP4 export metadata.',
        deliverablesQueue: [],
      },
      {
        id: 'st4', projectId: 'proj1', title: 'Thumbnail Design Package',
        taskType: 'Thumbnail Design', deadline: '2026-08-19T23:59:00Z',
        assignedEditorIds: ['e3'], status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/aurora-thumbs',
        deliverablesQueue: [],
      },
    ],
  },
  {
    id: 'proj2',
    title: 'TechFlow SaaS — Product Demo Series',
    clientName: 'TechFlow Inc.',
    createdAt: '2026-08-05T09:00:00Z',
    subtasks: [
      {
        id: 'st5', projectId: 'proj2', title: 'Motion Graphics Intro Package',
        taskType: 'Motion Graphics', deadline: '2026-09-02T23:59:00Z',
        assignedEditorIds: ['e1'], status: 'In Progress',
        deliverableLink: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
        deliverablesQueue: [
          {
            id: 'sub-st5-v1',
            version: 1,
            fileName: 'techflow_motion_intro_preview.aep',
            fileSizeBytes: 95000000,
            fileUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
            mimeType: 'application/octet-stream',
            notes: 'After Effects project archive and ProRes render.',
            submittedAt: '2026-08-30T16:00:00Z',
            submittedByEditorId: 'e1',
            status: 'In Review',
          },
        ],
      },
      {
        id: 'st6', projectId: 'proj2', title: 'Feature Walkthrough Video',
        taskType: 'YouTube Editing', deadline: '2026-08-24T23:59:00Z',
        assignedEditorIds: ['e3'], status: 'In Progress',
      },
      {
        id: 'st7', projectId: 'proj2', title: 'Social Teasers (4x)',
        taskType: 'Motion Graphics', deadline: '2026-08-21T23:59:00Z',
        assignedEditorIds: ['e2'], status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/techflow-teasers',
      },
    ],
  },
  {
    id: 'proj3',
    title: 'The Founder\'s Journey — Podcast Season 2',
    clientName: 'Growth Lab Media',
    createdAt: '2026-08-10T14:00:00Z',
    subtasks: [
      {
        id: 'st8', projectId: 'proj3', title: 'Episode 1–5 Full Edits',
        taskType: 'Podcast Editing', deadline: '2026-08-30T23:59:00Z',
        assignedEditorIds: ['e7'], status: 'Assigned',
      },
      {
        id: 'st9', projectId: 'proj3', title: 'YouTube Visualizer Clips',
        taskType: 'YouTube Editing', deadline: '2026-08-26T23:59:00Z',
        assignedEditorIds: ['e14'], status: 'In Progress',
      },
      {
        id: 'st10', projectId: 'proj3', title: 'Promo Reels (3x)',
        taskType: 'Reels Editing', deadline: '2026-08-23T23:59:00Z',
        assignedEditorIds: ['e5'], status: 'Ready for Review',
        deliverableLink: 'https://drive.google.com/founder-promo',
      },
    ],
  },
  {
    id: 'proj4',
    title: 'Discover Dubai — Tourism Campaign 2026',
    clientName: 'Dubai Tourism Board',
    createdAt: '2026-08-12T11:00:00Z',
    subtasks: [
      {
        id: 'st11', projectId: 'proj4', title: 'Cinematic Hero Film (90s)',
        taskType: 'Commercial Ads', deadline: '2026-09-05T23:59:00Z',
        assignedEditorIds: ['e10'], status: 'Assigned',
      },
      {
        id: 'st12', projectId: 'proj4', title: 'Color Grade & Finishing',
        taskType: 'Color Grading', deadline: '2026-09-10T23:59:00Z',
        assignedEditorIds: ['e10'], status: 'Assigned',
      },
      {
        id: 'st13', projectId: 'proj4', title: 'Social Cutdowns (6x)',
        taskType: 'Reels Editing', deadline: '2026-09-02T23:59:00Z',
        assignedEditorIds: ['e2', 'e13'], status: 'Assigned',
      },
    ],
  },
];

export const activityFeed: ActivityEvent[] = [
  { id: 'a1', type: 'submit_review', message: 'Elena Rodriguez submitted "Instagram Reel Series" for review', timestamp: '2026-08-18T09:45:00Z' },
  { id: 'a2', type: 'register', message: 'Noah Kim registered and submitted for verification', timestamp: '2026-08-18T05:30:00Z' },
  { id: 'a3', type: 'approve', message: 'You approved "Brand Commercial" by Marcus Chen', timestamp: '2026-08-17T16:20:00Z' },
  { id: 'a4', type: 'assign', message: 'Zara Ahmed assigned to "Cinematic Hero Film"', timestamp: '2026-08-17T14:30:00Z' },
  { id: 'a5', type: 'create_project', message: 'Project "Discover Dubai — Tourism Campaign" created', timestamp: '2026-08-12T11:00:00Z' },
  { id: 'a6', type: 'verify', message: 'James Wilson verified as an editor', timestamp: '2026-08-11T10:00:00Z' },
  { id: 'a7', type: 'send_back', message: 'Aria Patel\'s verification sent back with feedback', timestamp: '2026-08-10T15:00:00Z' },
];

export const adminCredentials = {
  email: 'admin@gogangs.com',
  password: 'admin1234',
};

export const allSkills: string[] = [
  'Reels Editing', 'YouTube Editing', 'Podcast Editing', 'Motion Graphics',
  'Commercial Ads', 'Corporate Videos', 'Wedding Videos', 'Color Grading', 'Thumbnail Design',
];

export const allSoftware: string[] = [
  'Adobe Premiere Pro', 'After Effects', 'DaVinci Resolve', 'Final Cut Pro',
  'Adobe Photoshop', 'Adobe Audition', 'CapCut',
];

export const allTaskTypes: string[] = [
  'Reels Editing', 'YouTube Editing', 'Podcast Editing', 'Motion Graphics',
  'Commercial Ads', 'Corporate Videos', 'Wedding Videos', 'Color Grading', 'Thumbnail Design',
];
